### ISSUE TITLE
Does not work on NA

### ISSUE THREAD

**Issue by Xordevv** [Namenlos0x9/tera-client-cli#1]
[client] Error: Request failed with status code 404, may you advice how to fix this?

**Comment by Namenlos0x9** [comment]
> [client] Error: Request failed with status code 404, may you advice how to fix this?

update the protocol version to the currrent patch version in version.json

**Comment by Xordevv** [comment]
Yes, it is already updated with 9303 patch and its protocol. 404 happened on auth-token, do i need to run npm install?

**Comment by Namenlos0x9** [comment]
> Yes, it is already updated with 9303 patch and its protocol. 404 happened on auth-token, do i need to run npm install?

post your console output here, censor everything personal.

**Comment by Xordevv** [comment]
Hi, the issue somehow is not happening when i try to run it again but now the issue is
`16:35:34 Info: [tera-proxy-game] Loaded 0 mods in 0ms
buffer.js:327
  throw new ERR_INVALID_ARG_TYPE(
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new from (buffer.js:327:9)
    at FakeClient.<anonymous> (C:\Workspace\modules\tera-client-cli-master\bin\cli\index.js:124:13)
    at FakeClient.emit (events.js:315:20)
    at FakeClient.onData (C:\Workspace\modules\tera-client-cli-master\node_modules\tera-proxy-game\clients\FakeClient.js:51:11)
    at Connection.sendClient (C:\Workspace\modules\tera-client-cli-master\node_modules\tera-proxy-game\connection\index.js:101:16)
    at Socket.<anonymous> (C:\Workspace\modules\tera-client-cli-master\node_modules\tera-proxy-game\connection\index.js:59:12)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10) {
  code: 'ERR_INVALID_ARG_TYPE'
}`

**Comment by Xordevv** [comment]
![image](https://user-images.githubusercontent.com/66426291/83865870-70865080-a759-11ea-9a08-91b0cdf3e672.png)

Just found i had this screenshot saved.

**Comment by PatrickSantoZZ** [comment]
NA fucked up the login some month ago. so CLI just works for EU/RU currently :)

**Comment by PatrickSantoZZ** [comment]
https://github.com/PatrickSantoZZ/youcantkillme newest cli updates. Idk why this repo don't get updated but if you wanna still use cli use this :)
